### ISSUE TITLE
local error: no renegotiation

### ISSUE THREAD

**Issue by samuelreh** [Clever/postgres-to-redshift#19]
I get `local error: no renegotiation` when dumping my larger tables. 

Might be related to https://github.com/golang/go/issues/5742

Any ideas on what I could do? Maybe I should write something that splits it into smaller COPY commands.

**Comment by schimmy** [comment]
Hi Samuel,

Yes - that ticket is very relevant! We've hit the same problems at Clever, and have worked around the crypto library's limitations by setting the `ssl_renegotiation_limit` to be infinite on the databases we use this with. See [this Stack Overflow](http://stackoverflow.com/questions/12332561/timeout-of-remote-connection-to-postgresql) post for details.

From a security standpoint, I would suggest that a very large or infinite renegotiation limit is more secure even than an implementation of renegotiation in the `crypto` library. It seems incredibly unlikely that any single database query would be large enough for cryptanalysis to take place successfully, and any renegotiation implementation would be complicated and risky. While we have additional security because we only run this within our private network, you should evaluate for yourself how high you want to set the `ssl_renegotiation_limit`, especially if your traffic traverses the internet.

Please let me know if you have any further questions,
-Colin

**Comment by samuelreh** [comment]
Thanks for the quick response. I'll give it a try.
